version: '3'
services:
  web:
    build: .
    network_mode: "bridge"
    ports:
      - "8000:80"
    volumes:
      - .:/usr/local/apache2/htdocs
    command: "/usr/local/apache2/bin/httpd -D FOREGROUND"
